/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as EcheancesRouteImport } from './routes/echeances'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer-orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CustomerOrdersIdRouteImport } from './routes/customer-orders.$id'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const EcheancesRoute = EcheancesRouteImport.update({
  id: '/echeances',
  path: '/echeances',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/customer-orders/',
  path: '/customer-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersIdRoute = CustomerOrdersIdRouteImport.update({
  id: '/customer-orders/$id',
  path: '/customer-orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/calendrier': typeof CalendrierRoute
  '/customers': typeof CustomersRoute
  '/echeances': typeof EcheancesRoute
  '/suppliers': typeof SuppliersRoute
  '/customer-orders/$id': typeof CustomerOrdersIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/customer-orders/': typeof CustomerOrdersIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/calendrier': typeof CalendrierRoute
  '/customers': typeof CustomersRoute
  '/echeances': typeof EcheancesRoute
  '/suppliers': typeof SuppliersRoute
  '/customer-orders/$id': typeof CustomerOrdersIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/customer-orders': typeof CustomerOrdersIndexRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/calendrier': typeof CalendrierRoute
  '/customers': typeof CustomersRoute
  '/echeances': typeof EcheancesRoute
  '/suppliers': typeof SuppliersRoute
  '/customer-orders/$id': typeof CustomerOrdersIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/customer-orders/': typeof CustomerOrdersIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/calendrier'
    | '/customers'
    | '/echeances'
    | '/suppliers'
    | '/customer-orders/$id'
    | '/orders/$id'
    | '/customer-orders/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/calendrier'
    | '/customers'
    | '/echeances'
    | '/suppliers'
    | '/customer-orders/$id'
    | '/orders/$id'
    | '/customer-orders'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/calendrier'
    | '/customers'
    | '/echeances'
    | '/suppliers'
    | '/customer-orders/$id'
    | '/orders/$id'
    | '/customer-orders/'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CalendrierRoute: typeof CalendrierRoute
  CustomersRoute: typeof CustomersRoute
  EcheancesRoute: typeof EcheancesRoute
  SuppliersRoute: typeof SuppliersRoute
  CustomerOrdersIdRoute: typeof CustomerOrdersIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echeances': {
      id: '/echeances'
      path: '/echeances'
      fullPath: '/echeances'
      preLoaderRoute: typeof EcheancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-orders/': {
      id: '/customer-orders/'
      path: '/customer-orders'
      fullPath: '/customer-orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-orders/$id': {
      id: '/customer-orders/$id'
      path: '/customer-orders/$id'
      fullPath: '/customer-orders/$id'
      preLoaderRoute: typeof CustomerOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CalendrierRoute: CalendrierRoute,
  CustomersRoute: CustomersRoute,
  EcheancesRoute: EcheancesRoute,
  SuppliersRoute: SuppliersRoute,
  CustomerOrdersIdRoute: CustomerOrdersIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
